# Generated by Django 4.0.5 on 2022-06-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_individualregister_anotherjoinaccountregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotherjoinaccountregister',
            name='kin_city',
        ),
        migrations.RemoveField(
            model_name='anotherjoinaccountregister',
            name='kin_country',
        ),
        migrations.RemoveField(
            model_name='anotherjoinaccountregister',
            name='kin_house_number',
        ),
        migrations.RemoveField(
            model_name='anotherjoinaccountregister',
            name='kin_name',
        ),
        migrations.RemoveField(
            model_name='anotherjoinaccountregister',
            name='kin_phone',
        ),
        migrations.RemoveField(
            model_name='anotherjoinaccountregister',
            name='kin_relationship',
        ),
        migrations.RemoveField(
            model_name='anotherjoinaccountregister',
            name='kin_state',
        ),
        migrations.RemoveField(
            model_name='anotherjoinaccountregister',
            name='kin_street_name',
        ),
    ]
