# Generated by Django 4.0.5 on 2022-07-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_photo_individualregister_individual_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessregister',
            name='checked',
        ),
        migrations.AddField(
            model_name='businessregister',
            name='typeofuser',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='individualregister',
            name='typeofuser',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
