# Generated by Django 4.0.5 on 2022-07-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_product_subproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SubProduct',
        ),
    ]
