# Generated by Django 4.0.5 on 2022-07-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='product_detail_title',
        ),
    ]
