# Generated by Django 4.0.5 on 2022-07-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_subproduct_product_detail_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='selling_price',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
