# Generated by Django 4.0.5 on 2022-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_orderplaced_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='product_title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
