# Generated by Django 4.0.5 on 2022-07-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_orderplaced_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='product_title',
        ),
    ]
