# Generated by Django 4.0.5 on 2022-07-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_orderplaced_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='product_title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
