# Generated by Django 4.0.5 on 2022-07-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_orderplaced_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='ordered_date_time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='ordered_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
