# Generated by Django 4.0.5 on 2022-07-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_orderplaced_ordered_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='payment_id',
            field=models.CharField(max_length=100),
        ),
    ]
