# Generated by Django 4.0.5 on 2022-07-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_orderplaced_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='ordered_date1',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
