# Generated by Django 4.0.5 on 2022-07-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_orderplaced_ordered_date1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='ordered_date1',
        ),
    ]
