# Generated by Django 4.0.5 on 2022-07-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_orderplaced_ordered_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='ordered_date1',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
