# Generated by Django 4.0.5 on 2022-07-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_orderplaced_ordered_date1'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
