# Generated by Django 4.0.5 on 2022-07-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_contact_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('banner_image', models.ImageField(upload_to='home/banner')),
            ],
        ),
        migrations.CreateModel(
            name='HomeExploreProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exp_image', models.ImageField(upload_to='home/exploreproduct')),
            ],
        ),
        migrations.CreateModel(
            name='HomeInfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_box1_title', models.CharField(max_length=200)),
                ('box1_description', models.TextField()),
                ('home_box2_title', models.CharField(max_length=200)),
                ('box2_description', models.TextField()),
                ('home_box3_title', models.CharField(max_length=200)),
                ('box3_description', models.TextField()),
                ('about_head', models.TextField()),
                ('about_description', models.TextField()),
                ('about_mission', models.TextField()),
                ('about_vision', models.TextField()),
                ('about_commitment', models.TextField()),
                ('about_image', models.ImageField(upload_to='home/homeinfosection')),
                ('hotline', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('market_update', models.CharField(max_length=200)),
                ('news', models.CharField(max_length=200)),
                ('sectornews', models.CharField(max_length=200)),
                ('upcomingevents', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomeTestinomials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('testi_image', models.ImageField(upload_to='home/testinomials')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWhatWeDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_image', models.ImageField(upload_to='home/whatwedo')),
                ('icon_image_hover', models.ImageField(upload_to='home/whatwedo')),
            ],
        ),
    ]
