# Generated by Django 4.0.5 on 2022-07-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_aboutteammembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_description', models.TextField()),
                ('box1_description', models.TextField()),
                ('box2_description', models.TextField()),
                ('about_image', models.ImageField(upload_to='home/homeinfosection')),
            ],
        ),
    ]
