# Generated by Django 4.0.5 on 2022-07-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_rename_box1_description_aboutinfosection_about_description2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='typeofuser',
            field=models.CharField(choices=[('corporate', 'corporate'), ('individual', 'individual')], max_length=200),
        ),
    ]
