# Generated by Django 4.0.5 on 2022-07-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_businessregister_bvn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfosection',
            name='contact_image',
            field=models.ImageField(default=None, upload_to='home/homeinfosection'),
            preserve_default=False,
        ),
    ]
