# Generated by Django 4.0.5 on 2022-07-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_homeinfosection_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeinfosection',
            name='contact_image',
        ),
    ]
