# Generated by Django 4.0.5 on 2022-07-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='modeofpayment',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
