# Generated by Django 4.0.5 on 2022-07-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_orderplaced_modeofpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='due_date',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='duration_month',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subproduct',
            name='duration_year',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
