# Generated by Django 4.0.5 on 2022-07-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_remove_subproduct_duration_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='duration_month',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='duration_year',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
