# Generated by Django 4.0.5 on 2022-07-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_subproduct_duration_month_subproduct_duration_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='duration_month',
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='duration_year',
        ),
    ]
