# Generated by Django 4.0.5 on 2022-07-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_subproduct_duration_month_subproduct_duration_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='due_date',
        ),
    ]
