# Generated by Django 4.0.5 on 2022-07-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_remove_orderplaced_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='due_date',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
