# Generated by Django 4.0.5 on 2022-07-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_orderplaced_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleofnews', models.CharField(max_length=500)),
                ('summaryofnews', models.TextField()),
                ('newspic', models.ImageField(upload_to='newspic')),
            ],
        ),
    ]
