# Generated by Django 4.0.5 on 2022-07-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_rename_summaryofnews_news_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='titleofnews',
            new_name='title',
        ),
    ]
